### ISSUE TITLE
cannot import name 'ABITypeError' from 'eth_abi.exceptions'

### ISSUE THREAD

**Issue by irmaster** [andelf/tronpy#12]
```
from tronpy import Tron

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/tronpy/__init__.py", line 1, in <module>
    from tronpy.tron import Tron
  File "/usr/local/lib/python3.8/site-packages/tronpy/tron.py", line 8, in <module>
    from tronpy.contract import Contract, ShieldedTRC20, ContractMethod
  File "/usr/local/lib/python3.8/site-packages/tronpy/contract.py", line 5, in <module>
    from tronpy.abi import trx_abi
  File "/usr/local/lib/python3.8/site-packages/tronpy/abi.py", line 4, in <module>
    from eth_abi.registry import BaseEquals
  File "/usr/local/lib/python3.8/site-packages/eth_abi/registry.py", line 15, in <module>
    from . import (
  File "/usr/local/lib/python3.8/site-packages/eth_abi/grammar.py", line 9, in <module>
    from eth_abi.exceptions import (

ImportError: cannot import name 'ABITypeError' from 'eth_abi.exceptions' (/usr/local/lib/python3.8/site-packages/eth_abi/exceptions.py)
```

**Comment by andelf** [comment]
https://github.com/ethereum/eth-abi/blob/master/eth_abi/exceptions.py#L82

Try ` pip3 install -U eth_abi`?

**Comment by MrNaif2018** [comment]
Probably no longer actual

**Comment by irmaster** [comment]
> https://github.com/ethereum/eth-abi/blob/master/eth_abi/exceptions.py#L82
> 
> Try ` pip3 install -U eth_abi`?

It's been a long time, thank you for your reply
