### ISSUE TITLE
tronpy.exceptions.ValidationError: Contract validate error : No contract or not a smart contract

### ISSUE THREAD

**Issue by SmallWangs** [andelf/tronpy#130]
Traceback (most recent call last):
  File "c:\Users\wang\Downloads\tron-api-python-main\test.py", line 37, in <module>
    print("broadcast and result =>", txn.broadcast().wait()) 
                                     ^^^^^^^^^^^^^^^
  File "C:\Users\wang\AppData\Local\Programs\Python\Python312\Lib\site-packages\tronpy\tron.py", line 184, in broadcast
    return TransactionRet(self._client.broadcast(self), client=self._client, method=self._method)    
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wang\AppData\Local\Programs\Python\Python312\Lib\site-packages\tronpy\tron.py", line 1079, in broadcast
    self._handle_api_error(payload)
  File "C:\Users\wang\AppData\Local\Programs\Python\Python312\Lib\site-packages\tronpy\tron.py", line 616, in _handle_api_error
    raise ValidationError(msg)
tronpy.exceptions.ValidationError: Contract validate error : No contract or not a smart contract

**Comment by MrNaif2018** [comment]
Most likely your constructed tx contains a wrong address
