### ISSUE TITLE
sig error

### ISSUE THREAD

**Issue by bigdragon8899** [andelf/tronpy#40]
Traceback (most recent call last):
  File "C:/projects/bitcoin/python_tron_api/study/example_wallet2.py", line 40, in <module>
    asyncio.run(transfer())
  File "C:\vnstudio\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\vnstudio\lib\asyncio\base_events.py", line 573, in run_until_complete
    return future.result()
  File "C:/projects/bitcoin/python_tron_api/study/example_wallet2.py", line 33, in transfer
    txn_ret = await txn.sign(priv_key).broadcast()
  File "C:\projects\bitcoin\python_tron_api\tronpy\async_tron.py", line 185, in broadcast
    return AsyncTransactionRet(await self._client.broadcast(self), client=self._client, method=self._method)
  File "C:\projects\bitcoin\python_tron_api\tronpy\async_tron.py", line 898, in broadcast
    self._handle_api_error(payload)
  File "C:\projects\bitcoin\python_tron_api\tronpy\async_tron.py", line 524, in _handle_api_error
    raise BadSignature(msg)
tronpy.exceptions.BadSignature: Validate signature error: sig error

**Comment by MrNaif2018** [comment]
Some of the parameters you passed were invalid. It is impossible to tell without more details
